# Generated by Django 3.0.7 on 2020-07-09 09:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import guidemap.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideMap',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('location_type', models.CharField(choices=[(guidemap.enums.LocationType['PARK'], '滑板場'), (guidemap.enums.LocationType['STORE'], '商店')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('traffic', models.CharField(blank=True, max_length=200)),
                ('openhours', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('update_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='GuideMapComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('update_dt', models.DateTimeField(blank=True, null=True)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidemaps', to='guidemap.GuideMap')),
            ],
        ),
    ]
