# Generated by Django 3.0.7 on 2020-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidemap', '0002_guidemap_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemap',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='guidemap',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=11),
        ),
        migrations.AlterField(
            model_name='guidemap',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=11),
        ),
        migrations.AlterField(
            model_name='guidemap',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='guidemapcomments',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='guidemapcomments',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
