# Generated by Django 3.0.7 on 2020-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidemap', '0004_guidemap_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidemapcomments',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
