# Generated by Django 3.0.7 on 2020-07-16 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import friendsgroup.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guidemap', '0007_auto_20200715_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('group_type', models.CharField(choices=[(friendsgroup.enums.FriendsGroupType['TUTORIAL'], '教學'), (friendsgroup.enums.FriendsGroupType['PRACTICE'], '交流')], max_length=50)),
                ('group_title', models.CharField(blank=True, max_length=50)),
                ('group_content', models.CharField(blank=True, max_length=500)),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=120)),
                ('join_user', models.CharField(blank=True, max_length=120)),
                ('possible_user', models.CharField(blank=True, max_length=120)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendsgroup_maps', to='guidemap.GuideMap')),
            ],
        ),
    ]
