# Generated by Django 3.0.7 on 2020-07-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsgroup', '0002_auto_20200718_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsgroup',
            old_name='uppper_limit',
            new_name='upper_limit',
        ),
    ]
