# Generated by Django 3.0.7 on 2020-07-18 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsgroup', '0003_auto_20200718_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsgroup',
            name='join_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='friendsgroup',
            name='possible_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
    ]
