# Generated by Django 3.0.7 on 2020-07-20 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendsgroup', '0004_auto_20200718_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsGroupComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_dt', models.DateTimeField(auto_now=True, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendsgroup', to='friendsgroup.FriendsGroup')),
            ],
        ),
    ]
