# Generated by Django 3.0.7 on 2020-07-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsgroup', '0005_friendsgroupcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsgroupcomments',
            old_name='username',
            new_name='comment_user',
        ),
    ]
