# Generated by Django 3.0.7 on 2020-07-15 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='map_add',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='map_comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='map_like',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
    ]
